### ISSUE TITLE
Show score for 2 users when they are juggling the same flake

### ISSUE THREAD

**Issue by lieuwex** [lieuwex/multisneeuw#1]
For more than 2 times and not twice by the same person

**Comment by tomsmeding** [comment]
Yes

**Comment by lieuwex** [comment]
done in 30c9ee271b6f3cba35543554ff21e0c575b9086c

**Comment by lieuwex** [comment]
well actually, @tomsmeding, do we want a 'reset' mechanism to break the combo when the same user dragged the same flake?

**Comment by tomsmeding** [comment]
Sounds like a good idea yeah
